services:
  redis:
    image: redis:7
    container_name: redis
    restart: always
    expose:
      - "6379"
    networks:
      - marsea_network

  backend:
    build: ./backend
    container_name: backend
    restart: always
    expose:
      - "8000"
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
    networks:
      - marsea_network

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    depends_on:
      - backend
    networks:
      - marsea_network

  npm:
    image: jc21/nginx-proxy-manager:latest
    container_name: npm
    restart: always
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - ./npm/data:/data
      - ./npm/letsencrypt:/etc/letsencrypt
    networks:
      - marsea_network

networks:
  marsea_network:
    driver: bridge
